# Originally generated by Django 4.1.6 on 2023-02-04. The field was first
# added as a Postgres-only ArrayField; a later migration (0008) converted
# it to JSONField. SQLite can't parse the ArrayField DDL ("near '[]':
# syntax error"), so on a fresh SQLite database the whole chain fails
# here.
#
# We rewrote this migration to create the column as JSONField directly.
# Production Postgres has this migration already recorded as applied in
# django_migrations, so the rewrite is a no-op there. On SQLite the
# column is created with a type the backend understands, and 0008's
# round-trip becomes a harmless no-op against an empty table.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_alter_station_naptan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="alternate_names",
            field=models.JSONField(null=True),
        ),
    ]
