# Generated by Django 4.2.29 on 2026-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0006_station_parent_station"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["name"], name="station_name_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["naptan_id"], name="station_naptan_idx"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["hub_naptan_id"], name="station_hub_naptan_idx"),
        ),
    ]
