# Generated by Django 4.1.7 on 2024-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["station_id", "source", "information", "resolved", "text"],
                name="incidents_r_station_c6be78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["resolved", "source"], name="incidents_r_resolve_255426_idx"
            ),
        ),
    ]
