# Generated by Django 4.1.7 on 2024-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_report_incidents_r_station_c6be78_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-start_time", "-id"]},
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["-start_time", "-id"], name="idx_start_time_id"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["station_id"], name="idx_station_id"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=[
                    "-start_time",
                    "-id",
                    "information",
                    "station_id",
                    "text",
                    "end_time",
                    "resolved",
                    "source",
                ],
                name="idx_covering",
            ),
        ),
    ]
