# Generated by Django 4.2.29 on 2026-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_alter_report_options_report_idx_start_time_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"ordering": ["-start_time", "-id"]},
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["resolved", "information", "-start_time", "-id"],
                name="incident_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["end_time"], name="incident_end_time_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["station_id", "resolved"], name="incident_station_resolved_idx"
            ),
        ),
    ]
