# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incidents",
            "0004_alter_incident_options_incident_incident_status_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="ML-predicted duration for this incident",
                null=True,
            ),
        ),
    ]
